version: '3'

services:
  database:
    image: postgres:15.1
    container_name: shopping_cart
    restart: always
    environment:
      POSTGRES_DB: shopping_cart_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres_data:
